apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: dev
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  namespace: dev
spec:
  selector:
    app: web-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwai-server
  namespace: dev
  labels:
    app: bwai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwai-server
  template:
    metadata:
      labels:
        app: bwai-server
    spec:
      containers:
      - name: busybox
        image: busybox:<INVALID_TAG>
        command: ["/bin/sh", "-c", "echo 'bwai-server: Error: Too many unresolved situations... Restarting.' && exit 1"]

# Staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-image-pod
  namespace: staging
spec:
  containers:
  - name: bad-image
    image: busybox:badtag  # Invalid tag
    command: ["/bin/sh", "-c", "echo '💔 Failed to download spinach... or love.' && sleep 3600"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-deploy
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop
  template:
    metadata:
      labels:
        app: crash-loop
    spec:
      containers:
      - name: crash
        image: busybox
        command: 
          - /bin/sh
          - -c
          - |
            echo '💚 Salads leaves Consumed: 3 leaves';
            echo '💔 Girls Messaged: 5';
            echo '😵‍💫 Crashes: 3';
            echo '🤖 Suresh: System Overwhelmed by Emotions. Exiting...';
            exit 1

---
apiVersion: v1
kind: Pod
metadata:
  name: missing-command-pod
  namespace: staging
spec:
  containers:
  - name: no-cmd
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - |
        echo "🤔 Pod waiting for Suresh to reply to all 5 girls...";
        exit 1
    # No command or args, can potentially fail if image has no default CMD
