apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: dev
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
  namespace: dev
spec:
  selector:
    app: web-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bwai-server
  namespace: dev
  labels:
    app: bwai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bwai-server
  template:
    metadata:
      labels:
        app: bwai-server
    spec:
      containers:
      - name: busybox
        image: busybox:<INVALID_TAG>

# Staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-image-pod
  namespace: staging
spec:
  containers:
  - name: bad-image
    image: busybox:badtag  # Invalid tag
    command: ["sleep", "3600"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crash-loop-deploy
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crash-loop
  template:
    metadata:
      labels:
        app: crash-loop
    spec:
      containers:
      - name: crash
        image: busybox
        command: ["/bin/sh", "-c", "exit 1"]  # Crash immediately

---
apiVersion: v1
kind: Pod
metadata:
  name: missing-command-pod
  namespace: staging
spec:
  containers:
  - name: no-cmd
    image: busybox:latest
    # No command or args, can potentially fail if image has no default CMD
